python train.py \
    --exp EndoMamba_MIX12_teacher \
    --gpu 0 \
    --batch_size 1 \
    --model endomambaseg_small \
    --root_path /root/lanyun-tmp/EndoMamba-master/data/CVC-ClinicVideoDB/ \
    --seed 11 \
    --n_skip 0 \
    --base_lr 1e-4 \
    --out_dir /root/lanyun-tmp/EndoMamba-master/videomamba/downstream/CVC-12kSegmentation/checkpoints/ \
    --wandb False